/**
 * IndustryFunnelPayload — the single source of truth for vertical acquisition surfaces.
 *
 * This schema is the output contract for the funnel_builder_agent AND the render contract
 * for the /industry/[slug] React route. Both are bound to this type — zero drift.
 *
 * Validation: Every agent-generated payload must pass funnelPayloadSchema.safeParse()
 * before being stored. Draft artifacts require explicit approval before the route serves them.
 *
 * See: docs/bot-builder/09-GATEWAY-VOICE-DOCTRINE.md, Industry_Funnel_Framework.md
 */
import { z } from "zod";
import { conversationWorkflowSchema } from "../conversationWorkflow";

// ── Sub-schemas ───────────────────────────────────────────────────────────────

export const funnelHeroSchema = z.object({
  headline: z.string().min(10).max(120),
  subheadline: z.string().min(20).max(300),
  ctaLabel: z.string().min(5).max(50),
  secondaryCtaLabel: z.string().max(50).optional(),
  eyebrow: z.string().max(60).optional(), // e.g. "For Nail Salons"
});

export const funnelPainPointSchema = z.object({
  headline: z.string().min(5).max(100),
  body: z.string().min(10).max(400),
  /** Optional data point or research signal, e.g. "62% of calls go to voicemail" */
  stat: z.string().max(120).optional(),
  icon: z.string().max(30).optional(), // lucide icon name
});

export const funnelDemoInputSchema = z.object({
  /** Placeholder text inside the business name field */
  namePlaceholder: z.string().max(60),
  /** Placeholder for city / state */
  locationPlaceholder: z.string().max(60),
  ctaLabel: z.string().min(5).max(60),
  supportText: z.string().max(200),
});

export const funnelOfferSchema = z.object({
  free: z.string().max(200),
  base: z.string().max(200),
  pack: z.string().max(200),
  packPrice: z.string().max(80),
  guarantee: z.string().max(200).optional(),
});

export const funnelTrustSignalSchema = z.object({
  text: z.string().min(5).max(200),
  source: z.string().max(80).optional(),
});

export const funnelSeoMetaSchema = z.object({
  title: z.string().min(10).max(80),
  description: z.string().min(20).max(200),
  keywords: z.array(z.string().max(50)).max(10),
  ogImage: z.string().max(200).optional(),
});

export const funnelSampleQuestionSchema = z.object({
  question: z.string().max(200),
  preview: z.string().max(300),
});

// ── Master payload schema ─────────────────────────────────────────────────────

export const funnelPayloadSchema = z.object({
  /** URL-safe slug: 'nail-salon', 'med-spa', 'hvac', 'dental', 'auto-service', 'hotel' */
  slug: z.string().regex(/^[a-z0-9-]+$/).min(3).max(40),

  /** Display name: 'Nail Salon', 'Medical Spa' */
  vertical: z.string().min(3).max(60),

  /** Internal category key matching conversationWorkflow.industryVertical */
  industryVertical: z.string().min(3).max(40),

  status: z.enum(["draft", "approved", "live"]).default("draft"),

  version: z.number().int().positive().default(1),

  /** SEO + social metadata */
  seoMeta: funnelSeoMetaSchema,

  /** Section 1: Hero */
  hero: funnelHeroSchema,

  /** Section 2: Pain points (3–5 required) */
  painPoints: z.array(funnelPainPointSchema).min(3).max(5),

  /** Section 3: Business test-drive input */
  demoInput: funnelDemoInputSchema,

  /**
   * Section 4: Sample questions the AI would answer for this vertical.
   * Used in the preview/demo section to show the product in vertical context.
   */
  sampleQuestions: z.array(funnelSampleQuestionSchema).min(3).max(6),

  /** Section 5: Activation tools copy */
  activationTools: z.object({
    headline: z.string().max(100),
    bullets: z.array(z.string().max(200)).min(2).max(5),
  }),

  /** Section 6: Offer structure */
  offer: funnelOfferSchema,

  /** Section 7: Trust signals */
  trustSignals: z.array(funnelTrustSignalSchema).min(2).max(6),

  /**
   * The ConversationWorkflow that fires when the visitor clicks "Test Drive".
   * Wired directly into the agent's system prompt on the demo page.
   * This is the structural guarantee that funnel copy and agent behavior are aligned.
   */
  conversationWorkflow: conversationWorkflowSchema,

  /** Anti-Platform hook — the specific sovereignty message for this vertical */
  sovereigntyHook: z.string().min(20).max(400),

  /** Generated by */
  generatedBy: z.string().default("funnel_builder_agent"),
  generatedAt: z.string().optional(),
});

export type FunnelPayload = z.infer<typeof funnelPayloadSchema>;
export type FunnelHero = z.infer<typeof funnelHeroSchema>;
export type FunnelPainPoint = z.infer<typeof funnelPainPointSchema>;
export type FunnelOffer = z.infer<typeof funnelOfferSchema>;

// ── Vertical registry ─────────────────────────────────────────────────────────

/**
 * The 6 priority verticals for Phase 4.
 * Slug is the URL key. industryVertical matches the ConversationWorkflow key.
 */
export const PRIORITY_VERTICALS = [
  { slug: "nail-salon",    vertical: "Nail Salon",    industryVertical: "nail_salon"    },
  { slug: "med-spa",       vertical: "Medical Spa",   industryVertical: "med_spa"       },
  { slug: "dental",        vertical: "Dental Office", industryVertical: "dental"        },
  { slug: "hvac",          vertical: "HVAC",          industryVertical: "hvac"          },
  { slug: "auto-service",  vertical: "Auto Service",  industryVertical: "auto_service"  },
  { slug: "hotel",         vertical: "Hotel",         industryVertical: "hotel"         },
] as const;

export type VerticalSlug = typeof PRIORITY_VERTICALS[number]["slug"];

/** Agent-access key pattern for funnel artifacts */
export const funnelArtifactKey = (slug: string, version = 1) =>
  `funnel_payload_${slug.replace(/-/g, "_")}_v${version}`;
