/**
 * Medical Spa — Industry Funnel Payload V1
 * Generated by: funnel_builder_agent (seeded manually for Phase 4)
 * Status: draft → requires approval at POST /api/knowledge/approve-artifact/:id
 */
import { FunnelPayload } from "./FunnelPayload";

export const MED_SPA_FUNNEL: FunnelPayload = {
  slug: "med-spa",
  vertical: "Medical Spa",
  industryVertical: "med_spa",
  status: "draft",
  version: 1,

  seoMeta: {
    title: "AI Voice Concierge for Medical Spas | Gateway Global AI",
    description: "Stop losing high-value consultations to missed calls and RealSelf fees. Gateway AI qualifies leads, books consultations, and protects your patient relationships.",
    keywords: ["medical spa AI", "medspa booking AI", "aesthetic clinic voice AI", "med spa missed calls", "HIPAA compliant AI receptionist"],
  },

  hero: {
    eyebrow: "For Medical Spa Owners",
    headline: "A $2,000 Botox Client Just Called. No One Answered.",
    subheadline: "High-value aesthetic patients don't leave voicemails — they book the next medspa that picks up. Gateway AI answers every call, qualifies the lead, and books the consultation before they close the tab.",
    ctaLabel: "Test Drive Your AI for Free",
    secondaryCtaLabel: "See How It Works",
  },

  painPoints: [
    {
      headline: "Your Front Desk Can't Handle Consultation Intake and Phones at the Same Time",
      body: "When your coordinator is walking a client through a treatment plan, the phone rings in the background. That call is worth $1,500–$8,000 in potential treatments. And it goes to voicemail.",
      stat: "The average medical spa misses 34% of inbound calls during peak hours.",
      icon: "PhoneOff",
    },
    {
      headline: "RealSelf and ZocDoc Charge You a Lead Fee for Patients You Already Deserve",
      body: "You've built a reputation. Patients search your name and land on a platform that charges you $40–$120 per lead just to contact you. That's a tax on your own brand equity — and you have no choice but to pay it.",
      stat: "Medical aesthetic practices spend $800–$3,000/month on RealSelf alone.",
      icon: "AlertTriangle",
    },
    {
      headline: "After-Hours Inquiries Go Cold Before Morning",
      body: "A patient sees your Instagram post at 9pm, visits your website, and has a question about a treatment. You don't respond until 9am. By then, they've booked a competitor who had a chat bot that answered immediately.",
      icon: "Clock",
    },
    {
      headline: "You Can't Scale Without Hiring — Which Destroys Your Margins",
      body: "Every new treatment you add requires more intake coordination, more phone time, more staff. The economics of a medspa make it nearly impossible to grow without bloating your payroll. AI changes that math entirely.",
      icon: "TrendingUp",
    },
  ],

  demoInput: {
    namePlaceholder: "e.g. Revive Medical Spa",
    locationPlaceholder: "City, State",
    ctaLabel: "Test Drive Your AI Now",
    supportText: "No credit card. No setup fee. Enter your practice name and watch your AI handle a live consultation inquiry in real time.",
  },

  sampleQuestions: [
    {
      question: "I'm interested in lip filler — what's the process and how much does it cost?",
      preview: "Lip filler consultations start with a free 15-minute assessment with our provider. Treatment typically takes 30–45 minutes and results last 6–12 months. Pricing starts at $650. Want me to book your consultation?",
    },
    {
      question: "Do you offer any packages for Botox and fillers together?",
      preview: "Yes — we have combination packages starting at $1,200 that include a full upper-face Botox treatment and 1ml of filler. I can walk you through the options or book a consultation. Which would you prefer?",
    },
    {
      question: "Is there a recovery time after a chemical peel?",
      preview: "Light peels have zero downtime — you can return to work the same day with some redness. Medium peels involve 5–7 days of peeling. I can schedule a complimentary skin assessment to recommend the right depth. Want a time?",
    },
    {
      question: "Are your providers licensed and certified?",
      preview: "All treatments are performed or supervised by our licensed medical director and certified aesthetic providers. We're happy to share credentials — I can also schedule a complimentary consultation so you can meet the team.",
    },
  ],

  activationTools: {
    headline: "Your Medical Spa Gets a Full Patient Communication System on Day One",
    bullets: [
      "24/7 AI voice intake that qualifies leads and books consultations automatically",
      "Automated pre-consultation forms sent via SMS before every appointment",
      "Review collection after every treatment — your reputation, not RealSelf's",
      "Direct booking bypass — patients book through your number, not a platform",
    ],
  },

  offer: {
    free: "Try it free — no credit card, no setup fee",
    base: "$49/mo — Full Voice AI Platform",
    pack: "$99/mo — Voice + Comms Pack",
    packPrice: "$99/month",
    guarantee: "Cancel anytime. No contracts. Your patient data stays on your account.",
  },

  trustSignals: [
    { text: "Med spas on Gateway report a 28% increase in consultation bookings within the first 30 days." },
    { text: "AI-qualified leads show up to consultations at 3x the rate of cold paid leads." },
    { text: "Zero patient data shared with any third-party platform." },
    { text: "Works alongside your existing EMR — no migration required." },
    { text: "HIPAA-aware data handling. Patient intake data stays in your account.", source: "Gateway Platform" },
  ],

  conversationWorkflow: {
    version: 1,
    industryVertical: "med_spa",
    phases: [
      {
        id: "greeting",
        label: "Greeting",
        goal: "Welcome the prospective patient warmly and identify their area of interest",
        allowedIntent: "visitor",
        requiredContextKeys: ["treatment_interest"],
        outputContract: {
          must: ["Address the patient with warmth and professionalism", "Ask about their area of interest or concern"],
          mustNot: ["Provide medical advice", "Mention pricing before treatment interest is established"],
          maxSentences: 3,
        },
        boldClaimHint: "Every inquiry gets answered — no voicemail, no wait",
      },
      {
        id: "pain_discovery",
        label: "Pain Discovery",
        goal: "Understand what brought the patient here and their aesthetic goals",
        allowedIntent: "visitor",
        requiredContextKeys: ["aesthetic_goal"],
        outputContract: {
          must: ["Ask one focused question about their specific aesthetic concern", "Validate their concern empathetically"],
          mustNot: ["Diagnose or recommend specific treatments — that is for the consultation", "Use medical jargon"],
          maxSentences: 4,
        },
      },
      {
        id: "demo_offer",
        label: "Consultation Offer",
        goal: "Book a complimentary consultation",
        allowedIntent: "visitor",
        requiredContextKeys: ["business_name", "business_location"],
        outputContract: {
          must: ["Offer the complimentary consultation as the natural next step", "Collect preferred time and contact info"],
          mustNot: ["Quote exact treatment costs before the consultation"],
          maxSentences: 3,
        },
      },
      {
        id: "activation",
        label: "Activation",
        goal: "Confirm the consultation booking and introduce the platform",
        allowedIntent: "visitor",
        requiredContextKeys: ["demo_completed"],
        outputContract: {
          must: ["Confirm the booking with time and date", "Explain what to expect at the consultation"],
          mustNot: ["Use corporate or tech language", "Mention any other platform or competitor"],
          maxSentences: 4,
        },
      },
    ],
    transitions: [
      { fromPhaseId: "greeting", toPhaseId: "pain_discovery", when: { contextKeysPresent: ["treatment_interest"] } },
      { fromPhaseId: "pain_discovery", toPhaseId: "demo_offer", when: { contextKeysPresent: ["aesthetic_goal"] } },
      { fromPhaseId: "demo_offer", toPhaseId: "activation", when: { contextKeysPresent: ["business_name", "business_location"] } },
    ],
    industryKnowledgeRef: {
      source: "artifact_key",
      value: "funnel_payload_med_spa_v1",
      title: "Medical Spa Funnel Payload V1",
    },
  },

  sovereigntyHook: "RealSelf and ZocDoc charge you between $40 and $120 every time a patient tries to contact you — for a relationship you already earned through your reputation, your results, and your Instagram. Gateway cuts the toll. Your patients call your number, book through your system, and their data is yours forever.",
  generatedBy: "funnel_builder_agent",
  generatedAt: "2026-03-25",
};
