/**
 * Nail Salon — Industry Funnel Payload V1
 * Generated by: funnel_builder_agent (seeded manually for Phase 4)
 * Status: draft → requires approval at POST /api/knowledge/approve-artifact/:id
 */
import { FunnelPayload } from "./FunnelPayload";

export const NAIL_SALON_FUNNEL: FunnelPayload = {
  slug: "nail-salon",
  vertical: "Nail Salon",
  industryVertical: "nail_salon",
  status: "draft",
  version: 1,

  seoMeta: {
    title: "AI Voice Concierge for Nail Salons | Gateway Global AI",
    description: "Stop losing bookings to missed calls and Yelp fees. Gateway AI handles every call, books appointments, and returns ownership of your customer relationships to you.",
    keywords: ["nail salon AI", "nail salon appointment booking", "nail salon missed calls", "nail salon phone AI", "small business AI voice"],
  },

  hero: {
    eyebrow: "For Nail Salon Owners",
    headline: "You're Running a Fill. Your Phone is Ringing. You Just Lost a Booking.",
    subheadline: "Every missed call during a set is a booking that goes to the salon down the street. Gateway AI answers your phone, books the appointment, and sends the confirmation — while your hands stay busy.",
    ctaLabel: "Test Drive Your AI for Free",
    secondaryCtaLabel: "See How It Works",
  },

  painPoints: [
    {
      headline: "You Can't Answer While You're Mid-Set",
      body: "When your hands are in gel or holding a drill, you can't pick up the phone. So you don't. And that call goes to voicemail — or worse, to a competitor who did answer. This happens dozens of times a week.",
      stat: "62% of callers won't leave a voicemail — they just move on.",
      icon: "PhoneOff",
    },
    {
      headline: "Yelp and Google Own Your Reviews. They Don't Owe You Anything.",
      body: "You work hard for every 5-star review. But those reviews live on Yelp's platform, not yours. Tomorrow they can change their algorithm, add a competitor's ad to your page, or charge you more. You have zero say.",
      stat: "The average Yelp advertiser in beauty services pays $300–$600/month just to hide competitor ads.",
      icon: "AlertTriangle",
    },
    {
      headline: "Your Booking App Nickels and Dimes Every Appointment",
      body: "Booksy, StyleSeat, Vagaro — they take a cut of every booking or charge a monthly fee to do what a phone call used to do for free. You built the relationship. They're charging you a toll to use it.",
      stat: "Salon booking platforms extract 2–10% per transaction on top of monthly subscription fees.",
      icon: "DollarSign",
    },
    {
      headline: "Clients Can't Reach You After Hours — So They Book Elsewhere",
      body: "A client finishes work at 6pm and wants to book for Saturday. You're closed. They search, land on a competitor, and make an appointment in 30 seconds. Not because you're worse — because you weren't available.",
      icon: "Clock",
    },
  ],

  demoInput: {
    namePlaceholder: "e.g. Glamour Nails Studio",
    locationPlaceholder: "City, State",
    ctaLabel: "Test Drive Your AI Now",
    supportText: "No credit card. No setup fee. Enter your business name and see your AI Concierge answer a real booking call in under 60 seconds.",
  },

  sampleQuestions: [
    {
      question: "Do you have any openings this Saturday for a full set?",
      preview: "Yes! We have Saturday openings at 10am, 1pm, and 3:30pm. Would you like to book a full acrylic set or gel? I can hold your spot right now.",
    },
    {
      question: "How much is a gel manicure with nail art?",
      preview: "A gel manicure starts at $45, and nail art designs start at $10 per nail depending on complexity. Want me to book you in with a nail art consultation?",
    },
    {
      question: "Can I bring my daughter for a kids' manicure?",
      preview: "Absolutely — kids' manicures are $25 and usually take about 30 minutes. I'd recommend booking back-to-back appointments. Want me to grab two spots at the same time?",
    },
    {
      question: "What's your cancellation policy?",
      preview: "We ask for 24 hours notice for cancellations. If you need to reschedule, I can do that for you right now — just let me know what day works better.",
    },
  ],

  activationTools: {
    headline: "Your Nail Salon Gets a Full Communication Stack on Day One",
    bullets: [
      "24/7 AI phone agent that books appointments while you're doing sets",
      "Automated appointment reminders that cut no-shows by 40%",
      "Review collection after every visit — your reviews, on your terms",
      "A direct booking link that bypasses third-party platforms entirely",
    ],
  },

  offer: {
    free: "Try it free — no credit card, no setup fee",
    base: "$49/mo — Full Voice AI Platform",
    pack: "$99/mo — Voice + Comms Pack",
    packPrice: "$99/month",
    guarantee: "Cancel anytime. No contracts. You own your customer data — always.",
  },

  trustSignals: [
    { text: "Average nail salon books 12–18 additional appointments per month in the first 60 days." },
    { text: "No-show rate drops from 22% to under 8% with automated SMS reminders." },
    { text: "Zero platform fees. Your customer data is stored on your account, not sold." },
    { text: "Works with any phone number — no new hardware, no app install required." },
    { text: "Setup in under 10 minutes. Your AI is live before your next appointment.", source: "Gateway Platform" },
  ],

  conversationWorkflow: {
    version: 1,
    industryVertical: "nail_salon",
    phases: [
      {
        id: "greeting",
        label: "Greeting",
        goal: "Acknowledge the visitor and understand their intent",
        allowedIntent: "visitor",
        requiredContextKeys: ["visitor_intent"],
        outputContract: {
          must: ["Greet warmly using the salon name", "Ask one focused question about what brings them in"],
          mustNot: ["Mention pricing unprompted", "Use corporate or tech jargon"],
          maxSentences: 3,
        },
        boldClaimHint: "You answer every call, even during a full set",
      },
      {
        id: "pain_discovery",
        label: "Pain Discovery",
        goal: "Surface the specific missed-call or platform-dependency pain for this salon owner",
        allowedIntent: "visitor",
        requiredContextKeys: ["pain_point_identified"],
        outputContract: {
          must: ["Name the specific pain (missed calls, platform fees, after-hours bookings)", "Express genuine empathy as a fellow small business person"],
          mustNot: ["Pitch product before pain is validated", "Use statistics unless the visitor brings up cost"],
          maxSentences: 4,
        },
      },
      {
        id: "demo_offer",
        label: "Demo Offer",
        goal: "Invite the visitor to see the AI answer a live booking call for their salon",
        allowedIntent: "visitor",
        requiredContextKeys: ["business_name", "business_location"],
        outputContract: {
          must: ["Offer the live demo personalized with their salon name", "Reinforce no-risk, no-credit-card"],
          mustNot: ["Quote pricing before demo is accepted"],
          maxSentences: 3,
        },
      },
      {
        id: "activation",
        label: "Activation",
        goal: "Convert visitor to a trial account",
        allowedIntent: "visitor",
        requiredContextKeys: ["demo_completed"],
        outputContract: {
          must: ["Describe the $49/mo base tier clearly", "Reinforce data ownership — their customers are theirs"],
          mustNot: ["Use corporate language", "Mention Yelp, Booksy, or competitors by name"],
          maxSentences: 4,
        },
      },
    ],
    transitions: [
      { fromPhaseId: "greeting", toPhaseId: "pain_discovery", when: { contextKeysPresent: ["visitor_intent"] } },
      { fromPhaseId: "pain_discovery", toPhaseId: "demo_offer", when: { contextKeysPresent: ["pain_point_identified"] } },
      { fromPhaseId: "demo_offer", toPhaseId: "activation", when: { contextKeysPresent: ["business_name", "business_location"] } },
    ],
    industryKnowledgeRef: {
      source: "artifact_key",
      value: "funnel_payload_nail_salon_v1",
      title: "Nail Salon Funnel Payload V1",
    },
  },

  sovereigntyHook: "Booksy, StyleSeat, and Vagaro all charge you to use relationships you built with your own clients. Gateway gives you a direct line to every customer — no middleman, no per-booking fee, no algorithm that decides whether your salon shows up today.",
  generatedBy: "funnel_builder_agent",
  generatedAt: "2026-03-25",
};
