
import { Booking, TripFocus } from "../types";

// Helper to format itinerary for export
export const formatItineraryForExport = (content: string, bookings: Booking[], tripFocus: TripFocus | null): string => {
    let output = `TRIP ITINERARY - Generated by TerraPlan AI\n`;
    output += `Date: ${new Date().toLocaleDateString()}\n\n`;
    
    if (tripFocus) {
        output += `TRIP FOCUS: ${tripFocus.name} (${tripFocus.type.toUpperCase()})\n`;
        if (tripFocus.location) output += `Location: ${tripFocus.location}\n`;
        if (tripFocus.uri) output += `Map: ${tripFocus.uri}\n`;
        output += `\n----------------------------------------\n\n`;
    }

    if (bookings.length > 0) {
        output += `CONFIRMED RESERVATIONS (${bookings.length})\n\n`;
        bookings.forEach(b => {
            output += `• ${b.title} (${b.type.toUpperCase()})\n`;
            output += `  Date: ${b.date} at ${b.time || 'N/A'}\n`;
            output += `  Ref: ${b.confirmationCode}\n`;
            if (b.guests) output += `  Guests: ${b.guests}\n`;
            output += `\n`;
        });
        output += `----------------------------------------\n\n`;
    }

    output += `NOTES & PLANS\n\n`;
    output += content;
    
    return output;
};

// Create a Google Doc
export const createGoogleDoc = async (accessToken: string, title: string, content: string): Promise<string | null> => {
    try {
        // 1. Create the Doc
        const createResponse = await fetch('https://docs.googleapis.com/v1/documents', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${accessToken}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                title: title
            })
        });

        if (!createResponse.ok) throw new Error('Failed to create doc');
        const docData = await createResponse.json();
        const documentId = docData.documentId;

        // 2. Insert Content
        const updateResponse = await fetch(`https://docs.googleapis.com/v1/documents/${documentId}:batchUpdate`, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${accessToken}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                requests: [
                    {
                        insertText: {
                            text: content,
                            location: {
                                index: 1
                            }
                        }
                    }
                ]
            })
        });

        if (!updateResponse.ok) throw new Error('Failed to insert content');
        
        return `https://docs.google.com/document/d/${documentId}/edit`;

    } catch (error) {
        console.error("Google Docs API Error:", error);
        return null;
    }
};

// Send Email via Gmail
export const sendGmail = async (accessToken: string, to: string, subject: string, content: string): Promise<boolean> => {
    try {
        // Construct raw MIME message
        const emailBody = [
            `To: ${to}`,
            `Subject: ${subject}`,
            'Content-Type: text/plain; charset="UTF-8"',
            'MIME-Version: 1.0',
            '',
            content
        ].join('\n');

        // Base64 encode (URL safe)
        const encodedEmail = btoa(unescape(encodeURIComponent(emailBody)))
            .replace(/\+/g, '-')
            .replace(/\//g, '_')
            .replace(/=+$/, '');

        const response = await fetch(`https://gmail.googleapis.com/upload/gmail/v1/users/me/messages/send`, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${accessToken}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                raw: encodedEmail
            })
        });

        if (!response.ok) throw new Error('Failed to send email');
        return true;

    } catch (error) {
        console.error("Gmail API Error:", error);
        return false;
    }
};
