-- Featured Partners table (GRN / Clear Voice)
-- Used by SmallBusinessInjector for preferential placement of partner businesses.
-- Note: partner_id is generated by the application (no extension required).

CREATE TABLE IF NOT EXISTS featured_partners (
    -- Core Identifiers (app provides UUID on insert)
    partner_id UUID PRIMARY KEY,
    grn_hotel_id VARCHAR(50) UNIQUE,
    google_place_id VARCHAR(255),

    -- Business Information
    business_name VARCHAR(255) NOT NULL,
    city_code VARCHAR(50) NOT NULL,
    category VARCHAR(100),

    -- "AI Selling Points" (The Pitch Engine)
    ai_hook VARCHAR(255),
    ai_tags JSONB,
    ai_story TEXT,
    ai_trigger_conditions JSONB,

    -- UI/UX Directives
    ui_theme_glow VARCHAR(20),
    badge_label VARCHAR(50) DEFAULT 'Certified Local',
    story_video_url VARCHAR(255),

    -- Metadata
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_featured_partners_city_code ON featured_partners(city_code);
CREATE INDEX IF NOT EXISTS idx_featured_partners_google_place_id ON featured_partners(google_place_id);
CREATE INDEX IF NOT EXISTS idx_featured_partners_is_active ON featured_partners(is_active);
